### ISSUE TITLE
how gyro aid klt track?

### ISSUE THREAD

**Issue by stihuangyuan** [daniilidis-group/msckf_mono#6]
in track_features function, we call calcOpticalFlowPyrLK for klt track, but the flag parameter default 0 is there an error? moreover in main loop, i think there has no difference between undistorted_pts and undistorted_prev_pts, so what the meaning?

**Comment by k-chaney** [comment]
Addressing the first part, at line 170 I use OPTFLOW_USE_INITIAL_FLOW. Which should set it properly, if not then this is a mistake on my end.
https://github.com/daniilidis-group/msckf_mono/blob/75a45e4219747087b2daf1379ad485ab3dde9ded/src/corner_detector.cpp#L170

This portion of the code is sloppy and that's something I'm working on addressing. One thing to keep in mind is that I don't keep around the undistorted versions of the points, only distorted since that's what is being used by KLT, so every time we give points to the outside we undistort them.

**Comment by stihuangyuan** [comment]
@k-chaney thanks for your reply. but for second question, according to codes, i doubt twoPointRansac() input two set keypoints maybe all this frame tracked points, but not from last and current frame.

**Comment by k-chaney** [comment]
https://github.com/daniilidis-group/msckf_mono/blob/75a45e4219747087b2daf1379ad485ab3dde9ded/src/corner_detector.cpp#L340-L380

This block here, undistorts the previous and current points, then transforms the points to the correct format and feeds into twoPointRansac. Which part of this do you see an issue in?

**Comment by GaoJunqiang** [comment]
@stihuangyuan in the original version, there is indeed such a problem since in the end of function TrackHandler::track_features(...) 
{
...
  prev_img_ = img;
  **prev_features_ = features;
  prev_feature_ids_ = feature_ids;**
  prev_time_ = cur_time_;
}
so prev_features, cur_features are all current frame's keypoints. It is easy to solve the problem.
But in the last version, code structure has many changes. I think there is no preblem on it. @k-chaney Last I would like to know when you finish the current code? Thanks.

**Comment by k-chaney** [comment]
Unfortunately it has become a side project recently, so I don't have a good timeline. I'm hoping to be able to put more time into it to finish up the ROS node.

**Comment by k-chaney** [comment]
I just got the ROS node merged into master a couple days ago. There is still some more work for it, but the main functionality is there.
