### ISSUE TITLE
How to work without Ground Truth?

### ISSUE THREAD

**Issue by bharat-robotics** [daniilidis-group/msckf_mono#9]
I collected bag file using husky and I have image and imu message. But I do not have the ground truth. I can dump the bag file in ASL format but the code seems to require ground truth. I do not need the absolute position of the robot in world coordinate frame. I only need the relative position of the camera from the starting point. 

Is there any workaround or already implemented code? Do I need to write my own wrapper?

**Comment by k-chaney** [comment]
I've emailed you I believe (sorry about that delay)  it is being worked on integrating this fully. Commit 1681ee7beb9dad30c670b73a4f65fff5739714bb has a working version of asl_msckf_no_ground_truth.cpp I've verified that this is working properly.

The main difference is that instead of just "stand_still_end", there is also a "stand_still_start". You want to find a window where there is no motion.

**Comment by bharat-robotics** [comment]
Yeah, we have been working on it. Thank you very much.

**Comment by k-chaney** [comment]
I have merged in a ros node and also the no ground truth version for the ASL dataset.

This ros node assumes that you are still at the start and then after the "stand_still_time" (default 8 seconds) it will start the MSCKF after initializing the IMU.

The ASL dataset version lets you specify a period, "stand_still_start" and "stand_still_end", to initialize the IMU with.
